/* Assignement Oper */

{
    let x = 10;
    let y = 20;


    //((x+=y) = (x = x + y))

    let z = x += y
    console.log(z);
    console.log(x);
    let zz = x -= y;
    console.log(zz); // x = xy x = 30 - 20 = 10
    let zzz = x *= y;
    console.log(zzz);
    let zzzz = x /= y;
    console.log(zzzz);
    let zzzzz = x %= y;
    console.log(zzzzz);
    let zzzzzz = x **= y;
    console.log(zzzzzz);

}

/* Comparision Opr */
{

    let x = 20;
    let y = 10;

    let z = x == y;
    console.log(z);
    let zz = x != y;
    console.log(zz);
    let zzz = x === y;
    console.log(zzz);
    let zzzz = x !== y;
    console.log(zzzz);
    let zzzzz = x > y;
    console.log(zzzzz);
    let zzzzzz = x >= y;
    console.log(zzzzzz);
    let zzzzzzz = x < y;
    console.log(zzzzzzz);
    let zzzzzzzz = x <= y;
    console.log(zzzzzzzz);

}

/* TypeOf Opr */

// let str = "SkillQode";
// let Num = 4165464;
// let bool = true;
// let arry = []
// let Obj = {}
// let Big = 7984378246723466n

// console.log(typeof(str));
// console.log(typeof(Num));
// console.log(typeof(bool));
// console.log(typeof(arry));
// console.log(typeof (Obj));
// console.log(typeof(Big));

/* string Opra */
    
// let x = 20;
// let y = "20";
// let zz 20;
// let xx 4;
// let yy 2;

// let z = zz + zz + zz + y + x + y + x + x + x + zz xx * yy / yy;
// let zzz = yy/yy

// console.log(z);
// console.log(zzz);
// console.log(1/0);
// console.log(-1/0);
// console.log("1"/0);
// console.log("1"/"1");
//  console.log("1" + ("1" * 20));

// Lecture End




// ........


let a = 10;
let b = 20;
let c = 5;
let d = a;

let e = a + c + d - d - a;
console.log(e);
let f = e + c + a - a - e;
console.log(f);
let g = c + c + b + b -e;
console.log(g);
let h = f - f - b + e - e;
console.log(h);
let i = f + (-f) + b + e + a + (-d);
console.log(i);
let j = f / f + e - e - h - g + e;
console.log(j);

